name: PR Verify

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: node:24.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test