name: PR Verify

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          make init

      - name: Run tests
        run: |
          make test
